# Generated by Django 2.2.5 on 2020-01-06 00:13

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_table1_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table2',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('kor', models.IntegerField()),
                ('eng', models.IntegerField()),
                ('mat', models.IntegerField()),
                ('regdate', models.DateField(auto_now_add=True)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
