# Generated by Django 2.2.5 on 2020-01-06 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_table2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table2',
            old_name='title',
            new_name='name',
        ),
    ]
