# Generated by Django 2.2.5 on 2020-01-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table2',
            name='classroom',
            field=models.CharField(max_length=3),
        ),
    ]
